config/routes.rb
Rails.application.routes.draw do

  root 'services#index'

  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :services

  resources :users,
    only: [:new, :create],
    path_names: { new: 'signup' }

end

app/models/service.rb
class Service < ActiveRecord::Base
  validates :make, :model, :year, :service_type, :date, :price, presence: true

  def self.per_page
    5
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :find_service, only: [:edit, :update]

  def index
    @services = Service.all.paginate(page: params[:page])
  end

  def edit
  end

  def update
    @service.update(service_params)
    redirect_to services_path,
      notice: "Your #{@service.year} #{@service.make} #{@service.model} drop off has been updated. Please call Robert or Kayla at 928-367-2630 to confirm drop off date."
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.save
    redirect_to services_path,
      notice: "Your #{@service.year} #{@service.make} #{@service.model} has been scheduled for drop off. Please call Robert or Kayla at 928-367-2630 to confirm drop off date."
  end

  private

  def service_params
    params.require(:service).permit(:year, :make, :model, :service_type, :date).merge(price: 70)
  end

  def find_service
    @service = Service.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:id] = user.id
      redirect_to root_path, notice: "Welcome back #{user.first_name.titleize}"
    else
      flash[:error] = 'Invalid username/password'
      render :login
    end
  end

  def destroy
    if user = current_user
      session[:id] = nil
      redirect_to root_path,
        notice: "#{user.email} has been logged out."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user =User.new(user_params)

    if @user.save
      session[:id] = @user.id
      redirect_to root_path,
        notice: "Thank you for signing up #{@user.first_name.titlecase}"
    else
      render.new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :email, :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_authentication.html.erb
<% if current_user %>
  Signed in as <%= current_user.email %>
  <%= link_to 'Logout', logout_path, method: :delete %>
<% else %>
  <%= link_to 'Signup', new_user_path %>
  <%= link_to 'Login', login_path %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Red Line llc</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Red Line llc", "#", :class => "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= render 'layouts/authentication' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/services/_form.html.erb
<%= form_for(@service) do |form| %>
  <p>
    <%= form.label :make %>
    <%= form.text_field :make %>
  </p>
  <p>
    <%= form.label :model %>
    <%= form.text_field :model %>
  </p>
  <p>
    <%= form.label :year %>
    <%= form.text_field :year %>
  </p>
  <p>
    <%= form.label :service_type %>
    <%= form.text_field :service_type %>
  </p>
  <p>
    <%= form.label :date %>
    <%= form.text_field :date %>
  </p>
  <p>
    <%= form.label :Price %>
    $70 per hour plus parts
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/services/edit.html.erb
<h1>Edit Service</h1>

<%= render 'form' %>

app/views/services/index.html.erb
<h1>Red Line llc Scheduled Drop-offs</h1>

<%= will_paginate @services %>
<table id='my_services' class="table table-hover">
  <tr>
    <th> Make </th>
    <th> Model </th>
    <th> Year </th>
    <th> Service Type </th>
    <th> Date </th>
  </tr>
  <% @services.each do |service| %>
  <tr>
    <td><%=service.make %></td>
    <td><%=service.model %></td>
    <td><%=service.year %></td>
    <td><%=service.service_type %></td>
    <td><%=service.date %></td>
    <td><%= link_to('Edit', edit_service_path(service)) %></td>

  </tr>
  <% end %>
</table>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h2>New Service</h2>

<%= form_for(@service) do |form| %>
  <p>
    <%= form.label :make %>
    <%= form.text_field :make %>
  </p>
  <p>
    <%= form.label :model %>
    <%= form.text_field :model %>
  </p>
  <p>
  <%= form.label :year %>
  <%= form.text_field :year %>
  </p>
  <p>
    <%= form.label :service_type %>
    <%= form.text_field :service_type %>
  </p>
  <p>
    <%= form.label :date %>
    <%= form.text_field :date %>
  </p>
  <p>
    <%= form.label :Price %>
    $70 per hour plus parts
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |form| %>
  <p>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </p>
  <p>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </p><p>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.label :password_confirmation, 'Password Confirmation' %>
    <%= form.password_field :password_confirmation %>
  </p>
  <p>
    <%= form.submit 'Signup' %>
  </p>
<% end %>

app/views/users/new.html.erb
<h2>Signup</h2>

<%= render 'form' %>